version: '2'

services:
  teamcity:
    restart: unless-stopped
    image: sashgorokhov/teamcity
    ports:
      - "0.0.0.0:8111:8111"
    volumes:
      - "/mnt/teamcity:/mnt/teamcity"

  teamcity_agent:
    restart: unless-stopped
    image: exira/teamcity-agent:4
    links:
      - "teamcity:teamcity"
    environment:
      SERVER_URL: teamcity:8111
